name = "cobol-worker"
type = "webpack"
account_id = "35a12ed87ac3233c64a7978aa97659fb"
route = "cobol.demos.cloudflare.com/api"
zone_id = "4263f1b1455a9130457118f26ea45cee"
webpack_config = "webpack.config.js"
main = "./src/index.js"
compatibility_date = "2024-04-26"
